//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string Action_download {
            get {
                return ResourceManager.GetString("Action_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Action_Load {
            get {
                return ResourceManager.GetString("Action_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from file.
        /// </summary>
        public static string Action_LoadFromFile {
            get {
                return ResourceManager.GetString("Action_LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from service.
        /// </summary>
        public static string Action_LoadFromService {
            get {
                return ResourceManager.GetString("Action_LoadFromService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Action_Remove {
            get {
                return ResourceManager.GetString("Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select cover.
        /// </summary>
        public static string Action_SelectCover {
            get {
                return ResourceManager.GetString("Action_SelectCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Book_Authors {
            get {
                return ResourceManager.GetString("Book_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Book_Description {
            get {
                return ResourceManager.GetString("Book_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication year.
        /// </summary>
        public static string Book_PublicationYear {
            get {
                return ResourceManager.GetString("Book_PublicationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Book_Title {
            get {
                return ResourceManager.GetString("Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the electronic version.
        /// </summary>
        public static string Book_URL {
            get {
                return ResourceManager.GetString("Book_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book catalog.
        /// </summary>
        public static string BookCatalog {
            get {
                return ResourceManager.GetString("BookCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book catalog editor.
        /// </summary>
        public static string BookCatalogEditor {
            get {
                return ResourceManager.GetString("BookCatalogEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string CatalogView_list {
            get {
                return ResourceManager.GetString("CatalogView_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopcase.
        /// </summary>
        public static string CatalogView_shopcase {
            get {
                return ResourceManager.GetString("CatalogView_shopcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view type.
        /// </summary>
        public static string CatalogView_type {
            get {
                return ResourceManager.GetString("CatalogView_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings.
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the service.
        /// </summary>
        public static string CouldNotConnectToService {
            get {
                return ResourceManager.GetString("CouldNotConnectToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for a list of books.
        /// </summary>
        public static string RequestRorListOfBooks {
            get {
                return ResourceManager.GetString("RequestRorListOfBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to save the book list.
        /// </summary>
        public static string RequestToSaveBookList {
            get {
                return ResourceManager.GetString("RequestToSaveBookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Section_Administration {
            get {
                return ResourceManager.GetString("Section_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string Section_Analytics {
            get {
                return ResourceManager.GetString("Section_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        public static string Section_Programming {
            get {
                return ResourceManager.GetString("Section_Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project management.
        /// </summary>
        public static string Section_ProjectManagement {
            get {
                return ResourceManager.GetString("Section_ProjectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Section_Testing {
            get {
                return ResourceManager.GetString("Section_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service address.
        /// </summary>
        public static string ServiceAddress {
            get {
                return ResourceManager.GetString("ServiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service port.
        /// </summary>
        public static string ServicePort {
            get {
                return ResourceManager.GetString("ServicePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service started.
        /// </summary>
        public static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped.
        /// </summary>
        public static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wcf service: books source.
        /// </summary>
        public static string WcfServerBooksSource {
            get {
                return ResourceManager.GetString("WcfServerBooksSource", resourceCulture);
            }
        }
    }
}
